### ISSUE TITLE
Count how many reads map to a reference

### ISSUE THREAD

**Issue by valeriafloral** [valeriafloral/Abies_fungal_endophytes#10]
I used BWA to map my quality-filtered reads against a reference genome and save the reads that did not match to that reference.

Firstly I made a reference index.

Then, I mapped my reads against the reference used the following command:

```
bwa mem -t 4 ../../metadata/Mmusculus_genome/mouse_cds.fa ../../data/trimmed/mouse1_univec_bwa.fastq > ../../data/trimmed/mouse1_mouse_bwa.sam
```

I obtained printed in the terminal the next message:

![image](https://user-images.githubusercontent.com/59807620/99343464-96a93400-2853-11eb-9123-278f6f2fda73.png)

By then I did not have an idea of which of these numbers were the reads that mapped to the reference.

I used **samtools** to convert the `.sam` file into `.bam`:

```
samtools view -bS ../../data/trimmed/mouse1_mouse_bwa.sam > ../../data/trimmed/mouse1_mouse_bwa.bam
```

Then using **samtools** I generated a `.fastq` file for all reads that mapped to the host reference genome:

```
samtools fastq -n -F 4 -0 ../../data/trimmed/mouse1_mouse_bwa_contaminats.fastq ../../data/trimmed/mouse1_mouse_bwa.bam
```

![Screenshot 2020-11-16 at 21 42 15](https://user-images.githubusercontent.com/59807620/99344029-b7be5480-2854-11eb-8566-b75cef9b23c1.png)

And then I generated another `.fastq` file for all reads that **DID NOT** map to the host reference genome:

```
samtools fastq -n -f 4 -0 ../../data/trimmed/mouse1_mouse_bwa.fastq ../../data/trimmed/mouse1_mouse_bwa.bam
```

![Screenshot 2020-11-16 at 21 43 30](https://user-images.githubusercontent.com/59807620/99344070-d3c1f600-2854-11eb-8599-02e9c2f47579.png)

So I would like to know the way to obtain a file (like a .logfile in **Trimmomatic**) that contains a summary of the number of reads that mapped and the number of reads that did not map to a reference.

I tried using a the `.flagstat`command from **samtools**:

```
samtools flagstat ../../data/trimmed/mouse1_mouse_bwa.bam > ../../data/reports/hostmap.txt
```

![image](https://user-images.githubusercontent.com/59807620/99403362-fd5c3b00-28af-11eb-9e3b-68383af61c25.png)

**Comment by camillethuyentruong** [comment]
Have you tried this `samtools idxstats` ?

**Comment by camillethuyentruong** [comment]
https://genomics.sschmeier.com/ngs-mapping/#mapping-statistics

**Comment by camillethuyentruong** [comment]
In `samtools view -c mapping/filename.unmapped.bam`, the `-c` flag counts the number of reads

**Comment by valeriafloral** [comment]
I found a solution using `stats`option from **samtools**

```
samtools stats ../../data/trimmed/mouse1_mouse_bwa.bam > ../../data/reports/hostmapstat.txt
```

And the output was:

![Screenshot 2020-11-17 at 9 19 39](https://user-images.githubusercontent.com/59807620/99408718-24b60680-28b6-11eb-8878-19e183c97cf3.png)

**Comment by ghost** [comment]
Great !

If you are still looking to print only the indicated lines you can try using:
` | grep -e pattern1 -e pattern2 `
substitute pattern1 and 2 for patterns specific to those lines, or use `egrep` instead and regular expressions.
