### ISSUE TITLE
Repository comments

### ISSUE THREAD

**Issue by solnavss** [valeriafloral/Abies_fungal_endophytes#14]
Hi, I have some comments that I hope will help you to improve your repo:

- [x] Add open-source license (https://choosealicense.com/)
- [x] Missing references
- [x] There are some typos in README
	Aims: ...tolerant and damaged fir individuals.
	Aims: ...from tolerant and damaged fir individuals.
	Workflow: ...16 samples(8 tolerante…)
- [x] There is some redundancy in README > Repository structure:
	This repository contains the following folders:
        Contains scripts to perform the analysis

**Comment by valeriafloral** [comment]
Thank you for your comments, Sol.

* I added the open-source license and the references.
* I am paying attention in typos and redundancy, but I'm not able to find the typo in "tolerant and damaged fir individuals" and in "from tolerant and damaged fir individuals". So I replaced *fir individuals* to *fir tress* 😅
