### ISSUE TITLE
Comments to improve repository

### ISSUE THREAD

**Issue by AliciaMstt** [valeriafloral/Abies_fungal_endophytes#15]
Hi,

Your repo is looking good, but the following points need attention:

README:

- [x] If the data is not going to be presented in data, explain this in the README, so that we know that what you are describing is the structure of the data even if it is not there. Also mention where (eg OSF, Dryad, etc) it would be available once published.
- [x] You mention that metadata contains the subdirectory `/reports` but this does not exist. 
- [x] You need to copy the metadata file from Vero's repository and include it in yours. Just mention that it comes from there. Also, explain each of the column names of the metadata file in your README.
- [x] Mention what is the file `Filterfiles.csv` of your metadata, and explain each column.
- [x] A directory tree (like Abelardo's) could be useful to exmplain your data directories.

Repo organization:

- [x] The README within /data is empty. 
- [x] The README within /bin is incomplete.

Summary:

- [x] You are missing a short md summary of your main results, which should include a short discussion.

R figure:

- [x] Your repo needs to include at least one figure made in R. It could be a plot from preliminary results, even the number of reads of something. This should be incorporated into your discussion.

Scritps:

- [x] Some of your scritps are empty. Please mention it in the README or comment the scritps with something like `# work in progress"`.

**Comment by valeriafloral** [comment]
Thank you for your comments, Alicia. I want to explain how I am coping with them:

**README**:

* I included the data folder in the .gitignore and explained that in the README file . In the file I mention that once the work conclude, the data will be available on OSF. In a dropdown I added the data folder structure needed to run my proposed workflow.
* I removed the extra files as `Filterfiles.csv` and only keeping in the repo the ones that are really informative. 
* This time I paid attention in only explain what is in the repo and not to mention folders that don't exist.

**Repo organization**:

* The files in the (now hidden) `/data` are huge! So I've decided to add this complete folder to the `.gitignore`.
* I'm still working on the scripts and there are some of them (as the assambly and gene prediction) that I haven't started yet. I marked those ones that aren't completed, approved, tested or started as **Work in progress**  in the `bin/README`.

**Summary and R figure**:

I added the [figures/Quality.md](https://github.com/valeriafloral/Abies_fungal_endophytes/blob/master/figures/Quality.md) file and show the results from the quality analysis. I used R to plot the paired and unpaired reads to easily visualize the unpaired reads percetage that will be discarded if I didn't use them.
