### ISSUE TITLE
Extract information and make a table

### ISSUE THREAD

**Issue by valeriafloral** [valeriafloral/Abies_fungal_endophytes#16]
## **Good morning!!!**

I have a [.txt](https://github.com/valeriafloral/Abies_fungal_endophytes/blob/master/metadata/reports/trimmomatic.txt) with a trimmomatic report, I want to plot the low quality reads, the paired, the R1 unpaired reads and the R2 unpaired reads. So I want to extract that information and put it in a table.

These are the names in the report:

**Input Read Pairs:** Total reads
**Both Surviving:** Paired
**Forward Only Surviving:** R1 unpaired reads
**Reverse Only Surviving:** R2 unpaired reads
**Dropped:** Low quality reads

I want a table like this to plot it in a stacked barplot:

![image](https://user-images.githubusercontent.com/59807620/104974895-d78e0800-59be-11eb-95d8-1693f335966a.png)

For the moment I've tried:

```
grep "DPVR*\|Input Read Pairs" trimmomatic.txt > test.txt
```

I obtained the lines were the file names are and the line were the reads are:

```
 -threads 4 -phred33 ../data/RAW/DPVR9_S187_L007_R1_001.fastq.gz ../data/RAW/DPVR9_S187_L007_R2_001.fastq.gz ../data/filter/outputs/DPVR9_S187_L007_R1_001_paired.fq.gz ../data/filter/outputs/DPVR9_S187_L007_R1_001_unpaired.fq.gz ../data/filter/outputs/DPVR9_S187_L007_R2_001_paired.fq.gz ../data/filter/outputs/DPVR9_S187_L007_R2_001_unpaired.fq.gz ILLUMINACLIP:../data/filter/adapters/TruSeq3-PE-2.fa:2:30:10 SLIDINGWINDOW:10:28 LEADING:28 TRAILING:28 MINLEN:50 HEADCROP:13
Input Read Pairs: 19753142 Both Surviving: 16822858 (85.17%) Forward Only Surviving: 2272090 (11.50%) Reverse Only Surviving: 271006 (1.37%) Dropped: 387188 (1.96%)
```

**Comment by solnavss** [comment]
So, for solving the issue we decided to focus on three steps:

1) Filter the STDOUT from trimmomatic to get the desired info
2) Make the table using dplyr
3) Make the graph on gglpot2

:)

**Comment by solnavss** [comment]
Here is an easy way with bash:

less -S segunda_1.txt | cut -d ' ' -f7,12,17,20 | sed -e 's/ /\t/g'

**Comment by solnavss** [comment]
grep "Input Read Pairs" trimmomatic.txt > segunda_1.txt

**Comment by valeriafloral** [comment]
To extract the samples name I used:

```
less trimmomatic.txt | grep '^D.*z$' | sed "s/_L007_R1_001.fastq.gz//"| sed "s/_L007_R2_001.fastq.gz//" 
```

**Comment by redgcko7** [comment]
to write a tab space using mac, we found out you have to press 'control v', then tab. Using this in the sed argument, we were able to get an output table of the columns we wanted, now to add the sample names as the first column...

Output table without sample names:
```
less -S segunda_1.txt | cut -d ' ' -f7,12,17,20 | sed -e 's/ /     /g'
17198787	2690873	252051	471219
42810194	6643866	706939	1091275
19754479	2918443	310165	479970
15171592	2288108	230428	372330
14750388	2257277	233035	376175
15892249	2611133	236734	412068
19718671	3108221	299649	571524
13035888	2129939	207288	324049
14365997	2248227	243684	398108
13210582	2163154	208352	371319
14572472	2191102	222777	362819
14323396	2142903	218819	370513
13473770	1972892	198337	324441
12606374	1940789	198784	314835
14830765	2420500	222193	373759
10173863	1946025	144035	270186
17304271	3202357	236340	475933
16822858	2272090	271006	387188
```

We were a little confused because it looks like not all the spaces were changed to tabs, but in reality they are tabs even though they look different sizes (...weird).

**Comment by solnavss** [comment]
```
less trimmomatic.txt | grep "DPVR*" | cut -d ' ' -f5 | sed "s/_L007_R1_001.fastq.gz//" | sed "s/..\/data\/RAW\///" > primera_1.txt
```

**Comment by solnavss** [comment]
[Here](https://unix.stackexchange.com/questions/16443/combine-text-files-column-wise) are some options for file merging as columns :)

**Comment by solnavss** [comment]
paste file1 file2 | column -s $'\t' -t

**Comment by redgcko7** [comment]
This line seems to merge them:
`paste primera_1.txt segunda2.txt > tercera_1.txt`

```
DPVR10_S188     17198787        2690873 252051  471219
DPVR11_S189     42810194        6643866 706939  1091275
DPVR12_S190     19754479        2918443 310165  479970
DPVR13_S191     15171592        2288108 230428  372330
DPVR14_S192     14750388        2257277 233035  376175
DPVR15_S193     15892249        2611133 236734  412068
DPVR16_S194     19718671        3108221 299649  571524
DPVR17_S195     13035888        2129939 207288  324049
DPVR18_S196     14365997        2248227 243684  398108
DPVR1_S179      13210582        2163154 208352  371319
DPVR2_S180      14572472        2191102 222777  362819
DPVR3_S181      14323396        2142903 218819  370513
DPVR4_S182      13473770        1972892 198337  324441
DPVR5_S183      12606374        1940789 198784  314835
DPVR6_S184      14830765        2420500 222193  373759
DPVR7_S185      10173863        1946025 144035  270186
DPVR8_S186      17304271        3202357 236340  475933
DPVR9_S187      16822858        2272090 271006  387188
```

**Comment by solnavss** [comment]
Sorry for all the mess... and thanks for all the fish ;) 

We almost close the issue.  Step 1: Filter the STDOUT from trimmomatic to get the desired table.

```
# To filter the samples ID, we use:

less trimmomatic.txt | grep "DPVR*" | cut -d ' ' -f5 | sed "s/_L007_R1_001.fastq.gz//" | sed "s/..\/data\/RAW\///" > ids.txt

# To filter information of each sample we use:
# Remember that sed on Mac doesn't recognize tabs as \t. You need to press [control] + [v] and then [tab] key. 

less trimmomatic.txt | grep "Input Read Pairs" | cut -d ' ' -f7,12,17,20 | sed -e 's/ /    /g' > info.txt

# Finally, to merge the files, we use: 

paste ids.txt info.txt > table.txt
```
The only thing missing is adding column names. You can try with nano or vim but also directly on R.

**Comment by valeriafloral** [comment]
When I import the `table.txt` with  the R command:

```
trimreads <- read.delim("./../data/table.txt", header = FALSE, sep = "\t")
```

I obtained a table that groups the reads in only one cell:

![Screenshot 2021-01-19 at 13 18 18](https://user-images.githubusercontent.com/59807620/105082988-f2618a80-5a59-11eb-954f-39345a9eb836.png)

So if I import it with the command:

```
trimreads <- read.delim("./../data/table.txt", header = FALSE, sep = " ")
```

I obtained a table that puts reads into separate cells, but add multiple columns, also it groups the sample name and the paired reads, so I used this R script to remove extra columns, separte the first column and add column names:


```
#take the cells with the reads
trimreads2 = subset(trimreads, select = c(V1, V5, V9, V13) ) # !!!The samples name is in the same cell with paired reads

#separate the 1st cell into "sample" and "paired"
finaltrimreads <- trimreads2 %>% separate(V1, c("sample", "paired"), sep = "\t", remove=TRUE) 

#name the columns
colnames(finaltrimreads) <- c("sample", "paired", "unpairedr1", "unpairedr2", "dropped") 
``` 


### The final table :DDDD
![image](https://user-images.githubusercontent.com/59807620/105086570-cdbbe180-5a5e-11eb-9ab3-35c7813a9bc6.png)

Then I used the library `dplyr` to transform it in a large table:

```
plotreads<- trimreads %>% gather(key = "observation", value="value", -c(1,))
```

![image](https://user-images.githubusercontent.com/59807620/105087370-fa242d80-5a5f-11eb-9390-893da7a6ea4d.png)


## Then I could ggplot it

![01_filteredreads](https://user-images.githubusercontent.com/59807620/105103250-e388d100-5a75-11eb-86ef-f235fa67cff0.jpeg)

The script to extract information from trimmomatic report is [here](https://github.com/valeriafloral/Abies_fungal_endophytes/blob/master/figures/bin/extract_trimmomatic.sh)
The script to import the table to R and make it ggploteable is [here](https://github.com/valeriafloral/Abies_fungal_endophytes/blob/master/figures/bin/cleanreadstable.R)
The script to make a stacked and percentage barplots is [here](https://github.com/valeriafloral/Abies_fungal_endophytes/blob/master/figures/bin/quality_barplot.R)




## THANK YOU FOR YOUR HELP!!!
