### ISSUE TITLE
Overrrepresented sequence that was not previously presented

### ISSUE THREAD

**Issue by valeriafloral** [valeriafloral/Abies_fungal_endophytes#9]
The preprocessing steps for the metatranscriptomics workflow consists of: 

![prepro](https://user-images.githubusercontent.com/59807620/99328975-d0be0a00-2842-11eb-96d0-6dcf13ab8cee.png)

After applying the filter processes **quality control, remove host reads and rRNA reads** and then replace the previously removed replicate reads back, I had the following **FastQC** overrepresented sequence that was no presented in the previous reports:

![image](https://user-images.githubusercontent.com/59807620/98748242-e1700b00-237e-11eb-936f-6f3b5b1197a5.png). 

These are the basic statistics from the three reports (**raw, trimming and filtered**):

![image](https://user-images.githubusercontent.com/59807620/98751317-855cb500-2385-11eb-95f2-e97680f971fd.png)

This is the complete [**raw**](https://drive.google.com/file/d/1HT8T-JYIOUCo0ExDtTz0YWiHcof0Yoyn/view?usp=sharing) data report and this is the [**trimming**](https://drive.google.com/file/d/18d8k4hQ9kgUXMxyIs-Z6V4teISdIPsuj/view?usp=sharing) report.

Also this is the complete [**quality filtered data**](https://drive.google.com/file/d/1yRpOJxOFrZk1FDoOg9FjYcm4itozVtK3/view?usp=sharing) report.

**Comment by camillethuyentruong** [comment]
Here is a FastQC [manual](https://rtsf.natsci.msu.edu/genomics/tech-notes/fastqc-tutorial-and-faq/#:~:text=Overrepresented%20Sequences&text=A%20sequence%20is%20considered%20overrepresented,to%20try%20to%20identify%20it.
)

Your sequence has only 78 reads and 0.1% (just over the limit for FastQC to consider it as overrepresented).

**Comment by camillethuyentruong** [comment]
Do you know if the sequence was present in the previous step or was added here? Is it a mouse sequence?

**Comment by bgrueda** [comment]
You should try to look into your FASTA sequences if this sequence is there using an `egrep` command in all the steps of your pipeline just to track it.

**Comment by bgrueda** [comment]
Another interesting thing is try to match the sequence to a probable targets.

**Comment by bgrueda** [comment]
You could continue your analysis and put a flag on this sequence, just in case in the next steps it could have a real meaning. 

TGTCTTTTTATCTTTCATGGTTTCCTGTTTCTGCGTTCATTTCTGGAATA

**Comment by valeriafloral** [comment]
> Do you know if the sequence was present in the previous step or was added here? Is it a mouse sequence?

It is not a mouse sequence. The sequence is not presented in the reference genome and in the samtools output that save the mouse reads.
